name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build-test-analyze-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  

      - name: Build and run tests
        run: mvn clean verify  

      - name: Qodana - Static Code Inspection
        uses: JetBrains/qodana-action@v2023.1.2
        with:
          project-dir: ./
          cache-dir: .qodana-cache
          upload-result: true         
          token: ${{ secrets.QODANA_TOKEN }}

      - name: Deploy to Azure Web App
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}   
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
