# -----------------------------------------------------------
# Build, configure and deploy JAR app to Azure Web App
# -----------------------------------------------------------
name: Build, configure and deploy JAR app to Azure Web App - alphasolutions8

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Miljø-variabler – kun brugt i workflow-context for læsbarhed
env:
  SPRING_DATASOURCE_URL:      ${{ secrets.AZURE_SQL_URL }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

jobs:
# -----------------------------------------------------------
# 1) Build-job
# -----------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read        # krævet af actions/checkout
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '17'

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar

# -----------------------------------------------------------
# 2) Deploy-job
# -----------------------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write        # nødvendig for OIDC-login
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZUREAPPSERVICE_CLIENTID_C4438B5D209B47C98018957A8AD7E319 }}
          tenant-id:      ${{ secrets.AZUREAPPSERVICE_TENANTID_7FEE318474BF40218949F9724B41CB08 }}
          subscription-id:${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B7F51401A4E34DE09696610274180055 }}

      # -----------------------------------------------------
      # Sæt App-settings + Connection-string på webappen
      # -----------------------------------------------------
      - name: Configure App settings & connection strings
        uses: Azure/appservice-settings@v1   # officiel action  [oai_citation:0‡GitHub](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/app-service/deploy-github-actions.md?utm_source=chatgpt.com)
        with:
          app-name: 'alphasolutions8'
          slot-name: 'Production'
          app-settings-json: |
            [
              { "name": "SPRING_DATASOURCE_URL",      "value": "${{ secrets.AZURE_SQL_URL }}" },
              { "name": "SPRING_DATASOURCE_USERNAME", "value": "${{ secrets.AZURE_SQL_USERNAME }}" },
              { "name": "SPRING_DATASOURCE_PASSWORD", "value": "${{ secrets.AZURE_SQL_PASSWORD }}" }
            ]
          connection-strings-json: |
            [
              { "name": "DefaultConnection",
                "value": "${{ secrets.AZURE_SQL_URL }};user=${{ secrets.AZURE_SQL_USERNAME }};password=${{ secrets.AZURE_SQL_PASSWORD }};",
                "type": "SQLAzure"
              }
            ]

      # (valgfrit) Flyway/Liquibase-migrering kan indsættes her

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'alphasolutions8'
          slot-name: 'Production'
          package: '*.jar'